import { Node, Edge } from '@xyflow/react';

export function generateAnsibleYAML(nodes: Node[], edges: Edge[]): string {
  // If the canvas is empty, return a comment
  if (nodes.length === 0) {
    return '# Your infrastructure canvas is currently empty.\n# Add nodes to generate an Ansible playbook.';
  }

  // Set up the Ansible Playbook boilerplate
  let yamlString = `---
# Ansible playbook generated by InfraCanvas
- name: Automated Infrastructure Provisioning
  hosts: all
  become: yes
  tasks:
\n`;

  // For v1, we will map through the nodes based on their order in the array.
  // (In a future update, we can use the 'edges' array to do a topological sort 
  // so the pipeline strictly follows the connection arrows).
  
  nodes.forEach((node) => {
    if (!node || !node.data || !node.data.label) {
      return;
    }

    const label = node.data.label as string;

    // Map each visual node to its corresponding Ansible YAML block
    if (label.includes('Update Packages')) {
      yamlString += `    # Update apt cache and upgrade packages
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist\n\n`;
    } 
    else if (label.includes('Install Nginx')) {
      yamlString += `    # Install Nginx Web Server
    - name: Install Nginx Web Server
      ansible.builtin.apt:
        name: nginx
        state: present\n\n`;
    } 
    else if (label.includes('Install Node.js')) {
      yamlString += `    # Install Node.js
    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present\n\n`;
    }
    else if (label.includes('Create PostgreSQL User')) {
      const dbUser = node.data.dbUser || '{{ db_user }}';
      const dbPass = node.data.dbPass || '{{ db_pass }}';

      yamlString += `    # Create PostgreSQL User
    - name: Create PostgreSQL user
      community.postgresql.postgresql_user:
        name: "${dbUser}"
        password: "${dbPass}"
        state: present\n\n`;
    }
    else if (label.includes('Install PostgreSQL')) {
      yamlString += `    # Install PostgreSQL Database
    - name: Install PostgreSQL
      ansible.builtin.apt:
        name: postgresql
        state: present\n\n`;
    }
    else if (label.includes('Open Port')) {
      const port = node.data.port || '{{ port_number }}';
      yamlString += `    # Open Port 80 in UFW
    - name: Open Port 80 in UFW
      ansible.builtin.ufw:
        port: "${port}"
        protocol: tcp
        action: allow\n\n`;
    }
    else if (label.includes('Copy .env')) {
      yamlString += `    # Copy .env file to server
    - name: Copy .env file to server
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'\n\n`;
    }
  });

  return yamlString;
}