import { Node, Edge } from '@xyflow/react';
import { generateAnsibleYAML } from './exportYaml';
import { DEFAULT_INSTANCE_PARAMS, DEFAULT_SG_PARAMS } from './terraformDefaults';

export interface FileItem {
  path: string;
  name: string;
  language: string;
  icon: string;
  iconColor?: string;
  lines: number;
  size: string;
  content: string;
}

export interface TerraformFiles {
  mainTf: string;
  variablesTf: string;
  outputsTf: string;
}

export function generateTerraformFiles(nodes: Node[]): TerraformFiles {
  const targetNode = nodes.find(n => n.data?.tech === 'Target');
  const awsRegion = (targetNode?.data?.region as string) || 'us-east-1';
  const environment = (targetNode?.data?.environment as string) || 'localstack';

  const providerBlock = environment === 'localstack'
    ? `terraform {
  backend "s3" {
    bucket                      = "infracanvas-state-bucket"
    key                         = "terraform.tfstate"
    region                      = "${awsRegion}"
    endpoints                   = { s3 = "http://localhost:4566" }
    use_path_style              = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
  }
}

provider "aws" {
  region                      = "${awsRegion}"
  access_key                  = "test"
  secret_key                  = "test"
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
  s3_use_path_style           = true

  endpoints {
    ec2 = "http://localhost:4566"
    s3  = "http://localhost:4566"
  }
}`
    : `terraform {
  backend "s3" {
    bucket = "infracanvas-state-bucket"
    key    = "terraform.tfstate"
    region = "${awsRegion}"
  }
}

provider "aws" {
  region = "${awsRegion}"
}`;

  const instanceNode = nodes.find(n => n.id.startsWith('aws_instance.web_server'));
  const parameters = (instanceNode?.data?.parameters as any) || DEFAULT_INSTANCE_PARAMS;
  const sgNode = nodes.find(n => n.id.startsWith('aws_security_group'));
  const sgParams = (sgNode?.data?.parameters as any) || DEFAULT_SG_PARAMS;
  const { sgName, httpPort, httpsPort, sshEnabled, allowedCidr } = sgParams;
  const { instanceName, amiId, instanceType, subnetId, rootVolumeSize, tags } = parameters;

  const subnetBlock = environment === 'localstack'
    ? `data "aws_vpc" "default" {
  default = true
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [data.aws_vpc.default.id]
  }
}`
    : '';
  const subnetIdExpr = environment === 'localstack'
    ? 'tolist(data.aws_subnets.default.ids)[0]'
    : `"${subnetId}"`;

  const mainTf = `# Generated by InfraFlow Visual Orchestration Platform
# Project: Project Alpha - Web-Server-Orchestration

${providerBlock}

${subnetBlock}

resource "aws_security_group" "${sgName}" {
  name        = "${sgName}"
  description = "Allows HTTP/HTTPS inbound & SSH access"

  ingress {
    from_port   = ${httpPort}
    to_port     = ${httpPort}
    protocol    = "tcp"
    cidr_blocks = ["${allowedCidr}"]
  }

  ingress {
    from_port   = ${httpsPort}
    to_port     = ${httpsPort}
    protocol    = "tcp"
    cidr_blocks = ["${allowedCidr}"]
  }${sshEnabled ? `

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["${allowedCidr}"]
  }` : ''}
}

resource "aws_instance" "${instanceName}" {
  ami           = "${amiId}"
  instance_type = "${instanceType}"
  subnet_id     = ${subnetIdExpr}

  vpc_security_group_ids = [aws_security_group.${sgName}.id]

  root_block_device {
    volume_size = ${rootVolumeSize}
  }

  tags = {
    ${tags.map((t: any) => `${t.key} = "${t.value}"`).join('\n    ')}
  }
}`;

  const variablesTf = `# Input variables for Terraform deployment

variable "aws_region" {
  type        = string
  default     = "us-east-1"
  description = "Target AWS region for deployment"
}

variable "instance_type" {
  type        = string
  default     = "${instanceType}"
  description = "EC2 instance size"
}`;

  const outputsTf = `# Output values to retrieve after deployment

output "web_server_public_ip" {
  value       = aws_instance.${instanceName}.public_ip
  description = "Public IP address of the web server"
}`;

  return { mainTf, variablesTf, outputsTf };
}

export async function downloadTerraformZip(nodes: Node[]): Promise<void> {
  const JSZip = (await import('jszip')).default;
  const { mainTf, variablesTf, outputsTf } = generateTerraformFiles(nodes);
  const zip = new JSZip();
  zip.file('main.tf', mainTf);
  zip.file('variables.tf', variablesTf);
  zip.file('outputs.tf', outputsTf);
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'terraform-config.zip';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateBundleFiles(nodes: Node[], edges: Edge[]): FileItem[] {
  // Reuse the extracted Terraform generator — single source of truth
  const { mainTf: mainTfContent, variablesTf: variablesTfContent, outputsTf: outputsTfContent } = generateTerraformFiles(nodes);

  // Read instanceName for hosts.ini (fallback to default)
  const instanceNode = nodes.find(n => n.id.startsWith('aws_instance.web_server'));
  const instanceName = ((instanceNode?.data?.parameters as any) || DEFAULT_INSTANCE_PARAMS).instanceName;

  // 4. Generate playbook.yml (dynamic Ansible playbook)
  const playbookYmlContent = generateAnsibleYAML(nodes, edges);

  // 5. Generate hosts.ini
  // TODO: The hosts.ini inventory file is a static placeholder. It should be dynamically constructed using inventory definitions and host variables defined on the workspace canvas.
  const colon = ':';
  const hostsIniContent = `[webservers]
web_server_1 ansible_host=aws_instance.${instanceName}.public_ip ansible_user=ubuntu

[all${colon}vars]
ansible_python_interpreter=/usr/bin/python3`;

  // 6. Generate deployment.yaml (Kubernetes)
  // TODO: The deployment.yaml Kubernetes manifest is entirely static. Implement a dynamic Kubernetes YAML compiler that reads specs (e.g. replicas, containers, labels) from the visual Kubernetes nodes on the canvas.
  const deploymentYamlContent = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80`;

  // 7. Generate README.md
  const readmeContent = `# InfraFlow Generated Bundle

This bundle contains the generated infrastructure code for **Project Alpha - Web-Server-Orchestration**.

## Structure
- \`terraform/\`: Infrastructure provisioning scripts
- \`ansible/\`: Configuration management playbooks
- \`k8s/\`: Kubernetes deployment manifests

## Usage
1. Initialize and apply Terraform: \`cd terraform && terraform init && terraform apply\`
2. Run Ansible playbook: \`cd ansible && ansible-playbook -i hosts.ini playbook.yml\``;

  const countLines = (str: string) => str.split('\n').length;
  const getSizeKb = (str: string) => `${(str.length / 1024).toFixed(1)} KB`;

  return [
    {
      path: 'terraform/main.tf',
      name: 'main.tf',
      language: 'HCL',
      icon: 'lucide:file',
      iconColor: 'text-primary',
      lines: countLines(mainTfContent),
      size: getSizeKb(mainTfContent),
      content: mainTfContent
    },
    {
      path: 'terraform/variables.tf',
      name: 'variables.tf',
      language: 'HCL',
      icon: 'lucide:file',
      iconColor: 'text-muted-foreground',
      lines: countLines(variablesTfContent),
      size: getSizeKb(variablesTfContent),
      content: variablesTfContent
    },
    {
      path: 'terraform/outputs.tf',
      name: 'outputs.tf',
      language: 'HCL',
      icon: 'lucide:file',
      iconColor: 'text-muted-foreground',
      lines: countLines(outputsTfContent),
      size: getSizeKb(outputsTfContent),
      content: outputsTfContent
    },
    {
      path: 'ansible/playbook.yml',
      name: 'playbook.yml',
      language: 'YAML',
      icon: 'lucide:clipboard',
      iconColor: 'text-[#00A4FF]',
      lines: countLines(playbookYmlContent),
      size: getSizeKb(playbookYmlContent),
      content: playbookYmlContent
    },
    {
      path: 'ansible/hosts.ini',
      name: 'hosts.ini',
      language: 'INI',
      icon: 'lucide:settings',
      iconColor: 'text-muted-foreground',
      lines: countLines(hostsIniContent),
      size: getSizeKb(hostsIniContent),
      content: hostsIniContent
    },
    {
      path: 'k8s/deployment.yaml',
      name: 'deployment.yaml',
      language: 'YAML',
      icon: 'lucide:layers',
      iconColor: 'text-[#326CE5]',
      lines: countLines(deploymentYamlContent),
      size: getSizeKb(deploymentYamlContent),
      content: deploymentYamlContent
    },
    {
      path: 'README.md',
      name: 'README.md',
      language: 'Markdown',
      icon: 'lucide:file',
      iconColor: 'text-muted-foreground',
      lines: countLines(readmeContent),
      size: getSizeKb(readmeContent),
      content: readmeContent
    }
  ];
}

export async function downloadZipBundle(nodes: Node[], edges: Edge[]): Promise<void> {
  const JSZip = (await import('jszip')).default;
  const files = generateBundleFiles(nodes, edges);
  const zip = new JSZip();

  files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'infraflow-bundle.zip';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
