import { Node, Edge } from '@xyflow/react';
import { generateAnsibleYAML } from './exportYaml';

export interface FileItem {
  path: string;
  name: string;
  language: string;
  icon: string;
  iconColor?: string;
  lines: number;
  size: string;
  content: string;
}

export function generateBundleFiles(nodes: Node[], edges: Edge[]): FileItem[] {
  // Find Terraform instance node if it exists on canvas to read parameters dynamically
  const instanceNode = nodes.find(n => n.id.startsWith('aws_instance.web_server'));
  
  const parameters = instanceNode?.data?.parameters as any || {
    instanceName: "web_server",
    amiId: "ami-0c7217cdde317cfec",
    instanceType: "t3.medium",
    subnetId: "subnet-0123456789abcdef0",
    rootVolumeSize: 50,
    tags: [
      { key: "Environment", value: "prod" },
      { key: "Role", value: "web" }
    ]
  };

  const { instanceName, amiId, instanceType, subnetId, rootVolumeSize, tags } = parameters;

  // Find Terraform security group node if it exists to read parameters dynamically
  const sgNode = nodes.find(n => n.id.startsWith('aws_security_group'));
  const sgParams = sgNode?.data?.parameters as any || {
    sgName: 'web_sg',
    sgDescription: 'Allows HTTP/HTTPS inbound & SSH access',
    ingressPorts: '80, 443'
  };

  const { sgName, sgDescription, ingressPorts } = sgParams;
  const portsList = (ingressPorts as string || '80, 443')
    .split(',')
    .map(p => p.trim())
    .filter(p => p !== '' && !isNaN(Number(p)))
    .map(p => Number(p));

  const ingressBlocks = portsList.length > 0
    ? portsList.map(port => `  ingress {
    from_port   = ${port}
    to_port     = ${port}
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }`).join('\n\n')
    : `  # No ingress ports configured`;

  // 1. Generate main.tf
  const mainTfContent = `# Generated by InfraFlow Visual Orchestration Platform
# Project: Project Alpha - Web-Server-Orchestration

provider "aws" {
  region = "us-east-1"
}

resource "aws_security_group" "${sgName}" {
  name        = "${sgName}"
  description = "${sgDescription}"

${ingressBlocks}
}

resource "aws_instance" "${instanceName}" {
  ami           = "${amiId}"
  instance_type = "${instanceType}"
  subnet_id     = "${subnetId}"

  vpc_security_group_ids = [aws_security_group.${sgName}.id]

  root_block_device {
    volume_size = ${rootVolumeSize}
  }

  tags = {
    ${tags.map((t: any) => `${t.key} = "${t.value}"`).join('\n    ')}
  }
}`;

  // 2. Generate variables.tf
  // TODO: The variables.tf file content is currently static. Future engineers should generate this file dynamically based on variables defined across all canvas nodes.
  const variablesTfContent = `# Input variables for Terraform deployment

variable "aws_region" {
  type        = string
  default     = "us-east-1"
  description = "Target AWS region for deployment"
}

variable "instance_type" {
  type        = string
  default     = "${instanceType}"
  description = "EC2 instance size"
}`;

  // 3. Generate outputs.tf
  // TODO: The outputs.tf file content is currently static. It should be dynamically generated to reference outputs (like public IPs or DNS names) of actual canvas resources.
  const outputsTfContent = `# Output values to retrieve after deployment

output "web_server_public_ip" {
  value       = aws_instance.${instanceName}.public_ip
  description = "Public IP address of the web server"
}`;

  // 4. Generate playbook.yml (dynamic Ansible playbook)
  const playbookYmlContent = generateAnsibleYAML(nodes, edges);

  // 5. Generate hosts.ini
  // TODO: The hosts.ini inventory file is a static placeholder. It should be dynamically constructed using inventory definitions and host variables defined on the workspace canvas.
  const hostsIniContent = `[webservers]
web_server_1 ansible_host=aws_instance.${instanceName}.public_ip ansible_user=ubuntu

[all\${":"}vars]
ansible_python_interpreter=/usr/bin/python3`;

  // 6. Generate deployment.yaml (Kubernetes)
  // TODO: The deployment.yaml Kubernetes manifest is entirely static. Implement a dynamic Kubernetes YAML compiler that reads specs (e.g. replicas, containers, labels) from the visual Kubernetes nodes on the canvas.
  const deploymentYamlContent = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80`;

  // 7. Generate README.md
  const readmeContent = `# InfraFlow Generated Bundle

This bundle contains the generated infrastructure code for **Project Alpha - Web-Server-Orchestration**.

## Structure
- \`terraform/\`: Infrastructure provisioning scripts
- \`ansible/\`: Configuration management playbooks
- \`k8s/\`: Kubernetes deployment manifests

## Usage
1. Initialize and apply Terraform: \`cd terraform && terraform init && terraform apply\`
2. Run Ansible playbook: \`cd ansible && ansible-playbook -i hosts.ini playbook.yml\``;

  const countLines = (str: string) => str.split('\n').length;
  const getSizeKb = (str: string) => `${(str.length / 1024).toFixed(1)} KB`;

  return [
    {
      path: 'terraform/main.tf',
      name: 'main.tf',
      language: 'HCL',
      icon: 'lucide:file',
      iconColor: 'text-primary',
      lines: countLines(mainTfContent),
      size: getSizeKb(mainTfContent),
      content: mainTfContent
    },
    {
      path: 'terraform/variables.tf',
      name: 'variables.tf',
      language: 'HCL',
      icon: 'lucide:file',
      iconColor: 'text-muted-foreground',
      lines: countLines(variablesTfContent),
      size: getSizeKb(variablesTfContent),
      content: variablesTfContent
    },
    {
      path: 'terraform/outputs.tf',
      name: 'outputs.tf',
      language: 'HCL',
      icon: 'lucide:file',
      iconColor: 'text-muted-foreground',
      lines: countLines(outputsTfContent),
      size: getSizeKb(outputsTfContent),
      content: outputsTfContent
    },
    {
      path: 'ansible/playbook.yml',
      name: 'playbook.yml',
      language: 'YAML',
      icon: 'lucide:clipboard',
      iconColor: 'text-[#00A4FF]',
      lines: countLines(playbookYmlContent),
      size: getSizeKb(playbookYmlContent),
      content: playbookYmlContent
    },
    {
      path: 'ansible/hosts.ini',
      name: 'hosts.ini',
      language: 'INI',
      icon: 'lucide:settings',
      iconColor: 'text-muted-foreground',
      lines: countLines(hostsIniContent),
      size: getSizeKb(hostsIniContent),
      content: hostsIniContent
    },
    {
      path: 'k8s/deployment.yaml',
      name: 'deployment.yaml',
      language: 'YAML',
      icon: 'lucide:layers',
      iconColor: 'text-[#326CE5]',
      lines: countLines(deploymentYamlContent),
      size: getSizeKb(deploymentYamlContent),
      content: deploymentYamlContent
    },
    {
      path: 'README.md',
      name: 'README.md',
      language: 'Markdown',
      icon: 'lucide:file',
      iconColor: 'text-muted-foreground',
      lines: countLines(readmeContent),
      size: getSizeKb(readmeContent),
      content: readmeContent
    }
  ];
}

export async function downloadZipBundle(nodes: Node[], edges: Edge[]): Promise<void> {
  const JSZip = (await import('jszip')).default;
  const files = generateBundleFiles(nodes, edges);
  const zip = new JSZip();

  files.forEach((file) => {
    zip.file(file.path, file.content);
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'infraflow-bundle.zip';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
