import { Node, Edge } from '@xyflow/react';

// Helper function to topologically sort canvas nodes based on connection edges
function getSortedNodes(nodes: Node[], edges: Edge[]): Node[] {
  const nodeMap = new Map<string, Node>();
  nodes.forEach(n => nodeMap.set(n.id, n));

  const adj = new Map<string, string[]>();
  const inDegree = new Map<string, number>();

  nodes.forEach(n => {
    adj.set(n.id, []);
    inDegree.set(n.id, 0);
  });

  edges.forEach(edge => {
    const u = edge.source;
    const v = edge.target;
    if (nodeMap.has(u) && nodeMap.has(v)) {
      adj.get(u)!.push(v);
      inDegree.set(v, inDegree.get(v)! + 1);
    }
  });

  const queue: string[] = [];
  // To keep a stable ordering for unconnected nodes, we iterate in original nodes order
  nodes.forEach(n => {
    if (inDegree.get(n.id) === 0) {
      queue.push(n.id);
    }
  });

  const sortedIds: string[] = [];
  while (queue.length > 0) {
    const u = queue.shift()!;
    sortedIds.push(u);

    const neighbors = adj.get(u) || [];
    neighbors.forEach(v => {
      inDegree.set(v, inDegree.get(v)! - 1);
      if (inDegree.get(v) === 0) {
        queue.push(v);
      }
    });
  }

  // Handle cycles or unvisited nodes by appending them in original order
  if (sortedIds.length < nodes.length) {
    const sortedSet = new Set(sortedIds);
    nodes.forEach(n => {
      if (!sortedSet.has(n.id)) {
        sortedIds.push(n.id);
      }
    });
  }

  return sortedIds.map(id => nodeMap.get(id)!).filter(Boolean);
}

export function generateAnsibleYAML(nodes: Node[], edges: Edge[]): string {
  // If the canvas is empty, return a comment
  if (nodes.length === 0) {
    return '# Your infrastructure canvas is currently empty.\n# Add nodes to generate an Ansible playbook.';
  }

  // Set up the Ansible Playbook boilerplate
  let headerString = `---
# Ansible playbook generated by InfraCanvas
- name: Automated Infrastructure Provisioning
  hosts: all
  become: yes
  tasks:

    # Configure dpkg to use unsafe IO for massive speedup in containers
    - name: Configure dpkg unsafe IO
      ansible.builtin.shell: |
        mkdir -p /etc/dpkg/dpkg.cfg.d
        echo "force-unsafe-io" > /etc/dpkg/dpkg.cfg.d/force-unsafe-io
      ignore_errors: yes

    # Clean up any stuck apt/dpkg locks if active
    - name: Clean up apt locks
      ansible.builtin.shell: |
        killall -9 apt apt-get dpkg 2>/dev/null || true
        rm -f /var/lib/dpkg/lock-frontend
        rm -f /var/lib/dpkg/lock
        rm -f /var/lib/apt/lists/lock
      ignore_errors: yes

    # Check for interrupted dpkg state
    - name: Check for interrupted dpkg state
      ansible.builtin.shell: dpkg -l | grep -E '^i[^i]'
      register: dpkg_check
      failed_when: false
      changed_when: false

    # Fix interrupted dpkg states only when needed
    - name: Fix interrupted dpkg states
      ansible.builtin.shell: dpkg --configure -a
      when: dpkg_check.rc == 0
      ignore_errors: yes

\n`;

  let tasksString = '';

  // Sort nodes topologically using the connections (edges)
  const sortedNodes = getSortedNodes(nodes, edges);

  sortedNodes.forEach((node) => {
    if (!node || !node.data || !node.data.label) {
      return;
    }

    const label = node.data.label as string;

    // Map each visual node to its corresponding Ansible YAML block
    if (label.includes('Update Packages')) {
      tasksString += `    # Update apt cache and upgrade packages
    - name: Update apt cache and upgrade packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist\n\n`;
    } 
    else if (label.includes('Install Nginx')) {
      tasksString += `    # Install Nginx Web Server
    - name: Install Nginx Web Server
      ansible.builtin.apt:
        name: nginx
        state: present\n\n`;
    } 
    else if (label.includes('Install Node.js')) {
      tasksString += `    # Install xz-utils dependency
    - name: Install xz-utils
      ansible.builtin.apt:
        name: xz-utils
        state: present

    # Download Node.js precompiled package
    - name: Download Node.js precompiled package
      ansible.builtin.get_url:
        url: https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz
        dest: /tmp/node-v18.16.0-linux-x64.tar.xz

    # Extract Node.tar.xz to /usr/local
    - name: Extract Node.tar.xz to /usr/local
      ansible.builtin.unarchive:
        src: /tmp/node-v18.16.0-linux-x64.tar.xz
        dest: /usr/local
        remote_src: yes
        extra_opts:
          - --strip-components=1\n\n`;
    }
    else if (label.includes('Create PostgreSQL User')) {
      const dbUser = node.data.dbUser || '{{ db_user }}';
      const dbPass = node.data.dbPass || '{{ db_pass }}';

      tasksString += `    # Install psycopg2 for PostgreSQL management
    - name: Install python3-psycopg2
      ansible.builtin.apt:
        name: python3-psycopg2
        state: present

    # Create PostgreSQL User
    - name: Create PostgreSQL user
      community.postgresql.postgresql_user:
        name: "${dbUser}"
        password: "${dbPass}"
        state: present\n\n`;
    }
    else if (label.includes('PostgreSQL') || label.includes('Postgres') || label.includes('Install PostgreSQL')) {
      tasksString += `    # Install PostgreSQL and psycopg2
    - name: Install PostgreSQL and python3-psycopg2
      ansible.builtin.apt:
        name:
          - postgresql
          - python3-psycopg2
        state: present\n\n`;

      const dbUser = node.data.dbUser || '{{ db_user }}';
      const dbPass = node.data.dbPass || '{{ db_pass }}';
      tasksString += `    # Create PostgreSQL User
    - name: Create PostgreSQL user
      community.postgresql.postgresql_user:
        name: "${dbUser}"
        password: "${dbPass}"
        state: present\n\n`;
    }
    else if (label.includes('Open Port')) {
      const port = node.data.port || '{{ port_number }}';
      tasksString += `    # Ensure UFW is installed
    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present

    # Open Port ${port} in UFW
    - name: Open Port ${port} in UFW
      ansible.builtin.ufw:
        rule: allow
        port: "${port}"
        proto: tcp
      ignore_errors: yes\n\n`;
    }
    else if (label.includes('Deploy Node App')) {
      const startCommand = (node.data.startCommand as string) || 'npm start';
      const appPort = (node.data.appPort as string) || '3000';
      const appName = 'app';

      tasksString += `    # Deploy Node.js Application
    - name: Copy application source code to server
      ansible.builtin.copy:
        src: __APP_SRC_DIR__/
        dest: /home/ubuntu/${appName}
        owner: ubuntu

    # Check if package.json exists in target directory
    - name: Check if package.json exists
      ansible.builtin.stat:
        path: /home/ubuntu/${appName}/package.json
      register: pkg_json

    # Install npm dependencies if package.json exists
    - name: Install npm dependencies
      ansible.builtin.command:
        cmd: npm install
        chdir: /home/ubuntu/${appName}
      when: pkg_json.stat.exists

    # Install pm2 process manager if package.json exists
    - name: Install pm2 process manager
      ansible.builtin.command:
        cmd: npm install -g pm2
      when: pkg_json.stat.exists

    # Start the application with pm2 if package.json exists
    - name: Start the application with pm2
      ansible.builtin.shell: pm2 delete ${appName} >/dev/null 2>&1 || true; PORT=${appPort} pm2 start "${startCommand}" --name ${appName}
      args:
        chdir: /home/ubuntu/${appName}
      when: pkg_json.stat.exists\n\n`;
    }
    else if (label.includes('Copy .env')) {
      tasksString += `    # Copy .env file to server
    - name: Copy .env file to server
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/.env
        owner: ubuntu
        group: ubuntu
        mode: '0600'\n\n`;
    }
  });

  let fullYaml = headerString + tasksString;
  // Find all unique variables using Regex
  const variableRegex = /{{\s*([\w_]+)\s*}}/g;
  const foundVariables = new Set<string>();
  let match;

  while ((match = variableRegex.exec(fullYaml)) !== null) {
    foundVariables.add(match[1]); // match[1] is the inner text without the brackets
  }

  // If variables were found, inject a 'vars:' block right before 'tasks:'
  if (foundVariables.size > 0) {
    let varsBlock = `  vars:\n`;
    foundVariables.forEach((v) => {
      varsBlock += `    ${v}: "REPLACE_ME_OR_USE_VAULT"\n`;
    });
    
    // Inject the vars block into the final string
    fullYaml = fullYaml.replace('  tasks:\n', `${varsBlock}\n  tasks:\n`);
  }

  return fullYaml;
}